### ISSUE TITLE
Add support for interactively specifying command timeout?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/nanorc#10]
In tests with artificial backpressure from the DataWriter module, I've seen the Stop command sent from _nanorc_ to the Dataflow App time out.

I've worked around this by hacking the send_command function in _appctrl.py_ to have a larger value for its timeout, but it would be cool if we could interactively tell commands what timeout to use

- e.g. `stop --timeout 30`

**Comment by eflumerf** [comment]
I'm going to ping this issue, as I've encountered similar issues with `boot`. I don't think this is a v2.10.0 issue, but I think I can take a look at it soon.
