### ISSUE TITLE
Port specification

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/nanorc#12]
The other day I was running on np04 machines and another user was running at the same time, on the same machine. 
Since it is not possible to use the same ports, launching nanorc was simply failing. 
Can we have the ports to be configurable? Even auto-configurable maybe?

**Comment by carloschavez** [comment]
Hi Marco, between me and Pierre discuss this issue,  and decided to implement a "port_offset"  parameters that will allow any new instance of nanorc to run in parallel on the same machine by offsetting the ports numbers by an integer amount. 
--port-offset <int> 

For the moment this will not handle the auto-configurable case however.

**Comment by bieryAtFnal** [comment]
I'm thinking that this change could be useful at ICEBERG, since it might allow us to run the global-timing nanorc and the daq-partition nanorc on the same computer, so I'm changing the Target Release to v2.10.2 as a suggestion/hope.  If folks object to this, please let me know.
