### ISSUE TITLE
Stderr output from processes should be logged

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/nanorc#35]
Based on my experience running the minidaqapp demo on the epdtdi-spack-build03 machine, it would be helpful if stderr messages could be added to the process logs. E.g., if there's a problem with ssh and the processes don't launch, currently the process logfiles are empty, 0 bytes. However, if stderr were included we'd get more info - in this case
```
Could not create directory '/.ssh' (Permission denied).
Failed to add the host to the list of known hosts (/.ssh/known_hosts).
spacknp@epdtdi-spack-build03.cern.ch: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).
```
The logfiles are very useful, but would be even more useful with stderr info included.

**Comment by plasorak** [comment]
Closing this, as this has been fixed.
