### ISSUE TITLE
Kerberos client

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/nanorc#45]
It's very hard to check if a kerberos ticket is valid and not expired. sometime this leads to error to send a log to ELisA.

**Comment by eflumerf** [comment]
`klist -s` will return 0 if the credential cache is valid: `https://web.mit.edu/kerberos/krb5-1.12/doc/user/user_commands/klist.html`

**Comment by plasorak** [comment]
In the end, this problem will be circumvented by adding an ELisA microservice.
