### ISSUE TITLE
"getenv" directive fails if envrionment variable unset

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/nanorc#8]
The "getenv" directive will cause `nanorc` to crash if the environment variable referenced is unset. It may be better behavior to print a warning and leave the variable unset in the child environment if this happens.

**Comment by ron003** [comment]
Maybe the configuration could support a "getenv_ifset" --- which would not need to produce a warning if
the variable is not in the environment

**Comment by plasorak** [comment]
The fix for this has been merged.
