### ISSUE TITLE
Add record command

### ISSUE THREAD

**Issue by floriangroetschla** [DUNE-DAQ/nanorc#9]
Add a new command `record` that gets the number of seconds to record as a runtime parameter. This will enable the minidaqapp to use the new recording capabilities from readout that write raw data from data link handlers to files for a specified amount of time.

**Comment by plasorak** [comment]
@roland-sipos is that still needed?

**Comment by plasorak** [comment]
This is going to be fixed via https://github.com/DUNE-DAQ/nanorc/issues/73
